// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2E036g1YIkxDufOp4eiPB6u5Uy-Bmrlw',
    appId: '1:159961987859:web:7ec8fb3607f75482e4f8e6',
    messagingSenderId: '159961987859',
    projectId: 'located-notifications',
    authDomain: 'located-notifications.firebaseapp.com',
    storageBucket: 'located-notifications.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtDdT5y5_IAgOZq3oYjbd4VQpk0H-g8I',
    appId: '1:159961987859:android:514b9587e86bb531e4f8e6',
    messagingSenderId: '159961987859',
    projectId: 'located-notifications',
    storageBucket: 'located-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2CQfOCCmbAMG3HC2YTLX8vAHSFNwO308',
    appId: '1:159961987859:ios:0a88c8c08ef0b764e4f8e6',
    messagingSenderId: '159961987859',
    projectId: 'located-notifications',
    storageBucket: 'located-notifications.appspot.com',
    iosClientId: '159961987859-muu6q05qet3u834inded76lmc1tlk9uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.locatedNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2CQfOCCmbAMG3HC2YTLX8vAHSFNwO308',
    appId: '1:159961987859:ios:0a88c8c08ef0b764e4f8e6',
    messagingSenderId: '159961987859',
    projectId: 'located-notifications',
    storageBucket: 'located-notifications.appspot.com',
    iosClientId: '159961987859-muu6q05qet3u834inded76lmc1tlk9uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.locatedNotifications',
  );
}
